kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: <host_example_com>:8443>/ocp412
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.12
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    - name: serverless-operator
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: stable
    - name: openshift-pipelines-operator-rh
      channels:
      - name: stable
    - name: kiali-ossm
      channels:
      - name: stable
    - name: jaeger-product
      channels:
      - name: stable
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
